# Generated by Django 5.2 on 2025-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankdetails_passwordresetcode_product_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtenreview',
            name='image',
        ),
        migrations.RemoveField(
            model_name='writtenreview',
            name='stars',
        ),
        migrations.AddField(
            model_name='writtenreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='writtenreview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writtenreview',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
